# Site settings
title: pentest.fun
url: "https://pentest.fun"


# Build settings
markdown: kramdown
highlighter: rouge
destination: docs

remote_theme: "taufderl/minimal-mistakes"
minimal_mistakes_skin: neon # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
repository: taufderl/pentest.fun

analytics:
  provider: google
  google:
    tracking_id: UA-121404671-3

search                   : true
search_full_content      : true
search_provider          : google 

defaults:
  - scope:
      type: pages
    values:
      sidebar:
        nav: "sidebar"
      classes: wide

plugins:
  - github-pages
include:
  - _pages
  - kb
exclude:
  - docs
  - .gitignore
  - Gemfile
  - Gemfile.lock
