# Site settings
title: pentest.fun
url: "https://pentest.fun"


# Build settings
markdown: kramdown
highlighter: rouge
destination: docs

remote_theme: "taufderl/minimal-mistakes"
minimal_mistakes_skin: neon # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
repository: taufderl/pentest.fun

search                   : true
search_full_content      : true
search_provider          : google
google:
  search_engine_id: 004312180320627585767:4dxhtdfl2ps

defaults:
  - scope:
      type: pages
    values:
      sidebar:
        nav: "sidebar"
      classes: wide

plugins:
  - github-pages
keep_files:
  - CNAME
include:
  - _pages
  - kb
  - assets
exclude:
  - docs
  - .gitignore
  - Gemfile
  - Gemfile.lock
